/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package liquidacion;



/**
 *
 * @author Administrador
 */
public class LiquidacionDeSueldos extends javax.swing.JFrame {
    
 int dni;   
 float basico,premio,descuento,cobrar;
Empleados e ;
 
 
    /**
     * Creates new form NewJFrame
     */
    public LiquidacionDeSueldos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btLiquidar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSueldoB = new javax.swing.JTextField();
        txtPremios = new javax.swing.JTextField();
        txtDescuentos = new javax.swing.JTextField();
        txtSueldoACobrar = new javax.swing.JTextField();
        btNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LIQUIDACION DE SUELDOS");

        jLabel2.setText("DNI :");

        jLabel3.setText("NOMBRE Y APELLIDO :");

        jLabel4.setText("SUELDO BASICO :");

        jLabel5.setText("PREMIOS :");

        jLabel6.setText("DESCUENTOS :");

        btLiquidar.setText("LIQUIDAR");
        btLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLiquidarActionPerformed(evt);
            }
        });
        btLiquidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btLiquidarKeyPressed(evt);
            }
        });

        jLabel7.setText("SUELDO A COBRAR :");

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniKeyPressed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtSueldoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoBActionPerformed(evt);
            }
        });
        txtSueldoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSueldoBKeyPressed(evt);
            }
        });

        txtPremios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPremiosKeyPressed(evt);
            }
        });

        txtDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentosActionPerformed(evt);
            }
        });
        txtDescuentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescuentosKeyPressed(evt);
            }
        });

        txtSueldoACobrar.setEditable(false);
        txtSueldoACobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoACobrarActionPerformed(evt);
            }
        });

        btNuevo.setText("NUEVO");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLiquidar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSueldoACobrar)
                                .addComponent(txtDescuentos)
                                .addComponent(txtPremios)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtSueldoB))
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btNuevo)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSueldoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPremios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btLiquidar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSueldoACobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btNuevo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtSueldoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSueldoBActionPerformed

    private void btLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLiquidarActionPerformed
        // TODO add your handling code here:
        
        dni = Integer.parseInt(txtDni.getText());
        basico = Integer.parseInt(txtSueldoB.getText());
        premio = Integer.parseInt(txtPremios.getText());
        descuento= Integer.parseInt(txtDescuentos.getText());
        cobrar= (basico+premio)-descuento;
        txtSueldoACobrar.setText("$ "+cobrar);
        
        e = new Empleados(dni,txtNombre.getText(),basico,premio,descuento,cobrar);
    }//GEN-LAST:event_btLiquidarActionPerformed

    private void txtSueldoACobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoACobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoACobrarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        // TODO add your handling code here:
        txtDni.setText("");
        txtNombre.setText("");
        txtPremios.setText("");
        txtSueldoACobrar.setText("");
        txtSueldoB.setText("");
        txtDescuentos.setText("");
        txtDni.requestFocus();
    }//GEN-LAST:event_btNuevoActionPerformed

    private void txtDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyPressed
        // TODO add your handling code here:
        char c = (char)evt.getKeyCode();
        if(c == evt.VK_ENTER){
            txtNombre.requestFocus();
        }
        if(c == evt.VK_ESCAPE){
            txtDni.setText("");
        }
    }//GEN-LAST:event_txtDniKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
          char c = (char)evt.getKeyCode();
        if(c == evt.VK_ENTER){
            txtSueldoB.requestFocus();
        }
        if(c == evt.VK_ESCAPE){
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtSueldoBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBKeyPressed
        // TODO add your handling code here:
          char c = (char)evt.getKeyCode();
        if(c == evt.VK_ENTER){
            txtPremios.requestFocus();
        }
        if(c == evt.VK_ESCAPE){
            txtSueldoB.setText("");
        }
    }//GEN-LAST:event_txtSueldoBKeyPressed

    private void txtPremiosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPremiosKeyPressed
        // TODO add your handling code here:
        char c = (char)evt.getKeyCode();
        if(c == evt.VK_ENTER){
            txtDescuentos.requestFocus();
        }
        if(c == evt.VK_ESCAPE){
            txtPremios.setText("");
        }
        
    }//GEN-LAST:event_txtPremiosKeyPressed

    private void txtDescuentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentosKeyPressed
        // TODO add your handling code here:
        char c = (char)evt.getKeyCode();
        if(c == evt.VK_ENTER){
            btLiquidar.requestFocus();
        }
        if(c == evt.VK_ESCAPE){
            txtDescuentos.setText("");
        }
    }//GEN-LAST:event_txtDescuentosKeyPressed

    private void btLiquidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btLiquidarKeyPressed
        // TODO add your handling code here:
        
      
        basico = Integer.parseInt(txtSueldoB.getText());
        premio = Integer.parseInt(txtPremios.getText());
        descuento= Integer.parseInt(txtDescuentos.getText());
        cobrar= (basico+premio)-descuento;
        txtSueldoACobrar.setText("$ "+cobrar);
        
    }//GEN-LAST:event_btLiquidarKeyPressed

    private void txtDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDescuentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquidacionDeSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquidacionDeSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquidacionDeSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquidacionDeSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquidacionDeSueldos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLiquidar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDescuentos;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPremios;
    private javax.swing.JTextField txtSueldoACobrar;
    private javax.swing.JTextField txtSueldoB;
    // End of variables declaration//GEN-END:variables
}
